language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.1
  fast_finish: false

env:
  global:
  - ENCRYPTION_LABEL: "7dec5f5b26df"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit --verbose --coverage-clover="output/code-coverage/clover.xml"

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover "output/code-coverage/clover.xml"

after_success:
  - if  [ $TRAVIS_PHP_VERSION = '7.1' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then script/travis-ci/deploy-documentation; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/919796e5e6af0283d419
    on_success: always
    on_failure: always
    on_start: always
